apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: data
type: Opaque
stringData:
  host: "postgres-service.data.svc.cluster.local"
  user: "postgres_user"
  password: "SuperSecret123"
